image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add docker-php-ext-install mysqli
- pip install docker-compose

build:
  stage: build
  script:
  - docker-compose -f docker-compose.yml build
