image:  docker

services:
    - docker:dind
    
stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
    script:
        - echo run test in this section
        
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - docker-compose up
    environment: master
    when: manual