image: docker

services:
    - docker:dind
    
stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
    script:
        - echo run test in this section
        
step-deploy-prod:
    stage: deploy
    only:
        - master
    script:
        - docker apt-get update -y
        - docker apt-get install -y docker-php-ext-install mysqli
        - docker-compose up -d --build
        
    environment: master
    when: manual