 # Agent VM image name
 vmImageName: 'ubuntu-latest'
 
 variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
    - test
    - deploy
    
test:
    stage: test
    only:
        - master
    script:
        - echo run test in this section

before_script:
  - docker version
  - docker-compose version
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    
step-deploy-prod:
    stage: deploy
      pool:
      vmImage: $(vmImageName)
    only:
        - master
    script:
        - docker-compose down
        - docker-compose build
        - docker-compose push
    
    environment: production
    when: manual
